sudo: required

language: sh

before_install:	
    - sudo apt-get update -q
    - export scversion="stable" # or "v0.4.7", or "latest"
    - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
    - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
    - sudo cp shellcheck-"${scversion}"/shellcheck /usr/bin/
    - /usr/bin/shellcheck --version
    # imagemagick
    - sudo apt install imagemagick 
    - sudo apt install ghostscript

    # since there is already data in the folder, the following comments are used only as proof of retrieval

    # worldcupplayerinfo.tsv
    # - wget -P chap0x04/tsvdata/  "https://c4pr1c3.gitee.io/linuxsysadmin/exp/chap0x04/worldcupplayerinfo.tsv"

    # web_log.tsv
#   - wget -P chap0x04/tsvdata/  "https://c4pr1c3.gitee.io/linuxsysadmin/exp/chap0x04/web_log.tsv.7z"
    - sudo apt install p7zip-full
    - 7z x chapx0x4/tsvdata/web_log.tsv.7z

script:
  - bash test.sh
  # Mission 1
  # HELP INFORMATION
  - bash chap0x04/shwork/image.sh --help
  # quality
  - bash chap0x04/shwork/image.sh -d chap0x04/img -q 50 
  # resolution
  - bash chap0x04/shwork/image.sh -d chap0x04/img -r 500
  # watermater
  - bash chap0x04/shwork/image.sh -d chap0x04/img -w "linux work"
  # prefix&&suffix
  - bash chap0x04/shwork/image.sh -d chap0x04/img --prefix "am"
  # -->jpg
  - bash chap0x04/shwork/image.sh -d chap0x04/img -j
  # mixed command
  - bash chap0x04/shwork/image.sh -d chap0x04/img -j -w "hello world" -s "am"
  
  # Mission 2-1
  - bash chap0x04/shwork/wcup.sh
  
  # Mission 2-2
  - bash chap0x04/shwork/wblog.sh "/images/MOSAIC-logosmall.gif"


after_script:
  - /usr/bin/shellcheck ./chap0x04/shwork/image.sh
  - /usr/bin/shellcheck ./chap0x04/shwork/wcup.sh
  - /usr/bin/shellcheck ./chap0x04/shwork/wblog.sh

after_failure:
  - id
  - pwd
  - df -h
  - cat error.log

notifications:
  email:
    on_success: never
